# -*- coding: utf-8 -*-
"""lab exp 6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VXU8yDFpuy2u1E1DeNikVhfAGPfGmZPa
"""

import cv2
from google.colab.patches import cv2_imshow

cap = cv2.VideoCapture('Sample.mp4')

while True:
    ret, frame = cap.read()
    if not ret:
        break

    slow = cv2.resize(frame, None, fx=0.5, fy=0.5)
    fast = cv2.resize(frame, None, fx=2.0, fy=2.0)

    cv2_imshow(slow)
    cv2_imshow(fast)

    # Press the stop button in Colab to end execution

cap.release()